<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder\**" />
    <Compile Remove="TurismoRural_API\**" />
    <Content Remove="Models\NewFolder\**" />
    <Content Remove="NewFolder1\**" />
    <Content Remove="NewFolder\**" />
    <Content Remove="TurismoRural_API\**" />
    <EmbeddedResource Remove="Models\NewFolder\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <EmbeddedResource Remove="TurismoRural_API\**" />
    <None Remove="Models\NewFolder\**" />

    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder\**" />
    <None Remove="TurismoRural_API\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\HomeController1.cs" />
    <Compile Remove="Models\UserApiService.cs" />
    <Compile Remove="Views\Admin\Class.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

</Project>
